#!/usr/bin/env bash

RUN_VIM="vim --clean --not-a-term"
RUN_TEST="${RUN_VIM} -S lib/run_test.vim"

pushd $(dirname $0) > /dev/null

echo "Running YouCompleteMe Vim tests"

RESULT=0

TESTS="$@"

if [ -z "$TESTS" ]; then
  TESTS=*.test.vim
fi

for t in ${TESTS}; do
  echo ""
  echo "%RUN: $t"
  TESTLOGDIR=$(pwd)/logs/$t

  # split on : into fileName and testName
  IFS=: read -s t T <<< "$t"

  if ${RUN_TEST} --cmd 'au SwapExists * let v:swapchoice = "e"' $t $T \
     && [ -f $t.res ];  then
    echo "%PASS: $t PASSED"
  else
    echo "%FAIL: $t FAILED - see $TESTLOGDIR"
    RESULT=1
  fi

  rm -rf $TESTLOGDIR
  mkdir -p $TESTLOGDIR
  for l in messages debuglog test.log *.testlog; do
    # In CI we can't view the output files, so we just have to cat them
    if [ -f $l ]; then
      if [ "$YCM_TEST_STDOUT" ]; then
        echo ""
        echo ""
        echo "*** START: $l ***"
        cat $l
        echo "*** END: $l ***"
      fi
      mv $l $TESTLOGDIR
    fi
  done

  rm -f $t.res
done

if [ -n "${COVERAGE}" ]; then
  covimerage write_coverage --source $(pwd)/.. --data-file .coverage.vim \
             .vim_profile

  mv .coverage.* ../
fi

popd > /dev/null

echo ""
echo "All done."


exit $RESULT
