pull_request_rules:
  - name: Automatic merge on Azure Pipelines and Reviewable successes
    conditions:
      - base=master
      - "#approved-reviews-by>=2"
      - status-success=ubuntu-20.04 - Python 3.6 x64
      - status-success=macos-10.15 - Python 3.6 x64
      - status-success=windows-2019 - Python 3.9 x64
      - status-success=windows-2019 - Python 3.9 x86
      - status-success=Vim tests - new
      - status-success=Vim tests - old
      - status-success=code-review/reviewable
    actions:
      merge:
        method: merge
        strict: true
      comment:
        message: Thanks for sending a PR!
  - name: Manual merge on Azure Pipelines and Maintainer Override
    conditions:
      - base=master
      - status-success=ubuntu-20.04 - Python 3.6 x64
      - status-success=macos-10.15 - Python 3.6 x64
      - status-success=windows-2019 - Python 3.9 x64
      - status-success=windows-2019 - Python 3.9 x86
      - status-success=Vim tests - new
      - status-success=Vim tests - old

      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"

      - label="Ship It!"
    actions:
      merge:
        method: merge
        strict: true
      comment:
        message: Thanks for sending a PR!
