pull_request_rules:
  - name: Automatic merge on Azure Pipelines and Reviewable successes
    conditions:
      - base=master
      - "#approved-reviews-by>=2"
      - status-success=Linux - Python 3.6 x64
      - status-success=macOS - Python 3.6 x64
      - status-success=Windows - Python 3.9 x64
      - status-success=Windows - Python 3.9 x86
      - status-success=Vim tests - new
      - status-success=Vim tests - old
    actions:
      merge:
        method: merge
        strict: true
      comment:
        message: Thanks for sending a PR!
  - name: Manual merge on Azure Pipelines and Maintainer Override
    conditions:
      - base=master
      - status-success=Linux - Python 3.6 x64
      - status-success=macOS - Python 3.6 x64
      - status-success=Windows - Python 3.9 x64
      - status-success=Windows - Python 3.9 x86
      - status-success=Vim tests - new
      - status-success=Vim tests - old

      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"

      - label="Ship It!"
    actions:
      merge:
        method: merge
        strict: true
      comment:
        message: Thanks for sending a PR!
