#!/usr/bin/env bash

set -e

if [ "$1" = "--continue" ]; then
  OPTS=""
else
  OPTS="--no-cache"
fi

ARCH=$(uname -m)

docker build ${OPTS} -t youcompleteme/ycm-vim-${ARCH}-py3:manual \
                     --build-arg YCM_PYTHON=py3 \
                     --build-arg ARCH=${ARCH} \
                     image/
