#!/usr/bin/env bash

CONTAINER=youcompleteme/ycm-vim-py3:manual

pushd $(dirname $0)
  docker run --mount src="$(pwd)/../../../",target=/home/dev/YouCompleteMe,type=bind \
             -it ${CONTAINER} \
             "$@"
popd
