#!/usr/bin/env bash

ARCH=$(uname -m)
CONTAINER=youcompleteme/ycm-vim-${ARCH}-py3:manual

pushd $(dirname $0)
  docker run --mount src="$(pwd)/../../../",target=/home/dev/YouCompleteMe,type=bind \
             -it ${CONTAINER} \
             "$@"
popd
