#!/usr/bin/env bash

set -e

if [ "$1" = "--continue" ]; then
  OPTS=""
else
  OPTS="--no-cache"
fi

ARCH=$(uname -m)

docker build ${OPTS} -t youcompleteme/ycm-vim-${ARCH}-py3:test \
                     --build-arg YCM_VIM_PYTHON=python3 \
                     image/
